[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/kube-scheduler"
  version = "kubernetes-1.18.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  # version = "v1.18.2"
  revision = "52c56ce7a8272c798dbc29846288d7cd9fbae032"

[[constraint]]
  name = "k8s.io/utils"
  revision = "a9aa75ae1b89e1b992c33383f48e942d97e52dae"

[[override]]
  name = "k8s.io/klog"
  version = "v1.0.0"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  # temporary solution until scheduler framework is fully migrate to a seperate community repository
  source = "github.com/ingvagabund/structured-merge-diff"
  revision = "0748688655b33b0f65ddd7f026f9a00bbab62594"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "bf4fb3bd569c8c84504d856598edbc66c10d8744"

[[override]]
  name = "k8s.io/csi-translation-lib"
  version = "kubernetes-1.18.2"

[[override]]
  name = "github.com/coreos/etcd"
  revision = "v3.4.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "kubernetes-1.18.2"

[[override]]
  name = "google.golang.org/grpc"
  revision = "v1.23.0"

[[override]]
  name = "golang.org/x/text"
  version = "v0.3.3"

[prune]
  go-tests = true
  unused-packages = true
